import { CountryCode, MarketConfig } from '../types/market';

export const DEFAULT_COUNTRY_CODE: CountryCode = 'CO';

const defaultShippingPolicy = {
  processingTime: "Procesamos tu pedido en 1–3 días hábiles.",
  deliveryEstimate: "El tiempo de entrega depende del país de destino y del método de envío seleccionado. Recibirás información de seguimiento para consultar el estado de tu pedido.",
  disclaimer: "Los tiempos de entrega son estimados y pueden variar por procesos aduaneros, transportistas u otras circunstancias fuera de nuestro control.",
};

const defaultReturnsPolicy = {
  condition: "Las condiciones de devolución dependen del país desde el que realizas la compra y de la normativa aplicable.",
  instructions: "Si deseas devolver un producto, contáctanos antes de enviarlo para indicarte el procedimiento correspondiente.",
};

const defaultWarrantyPolicy = {
  damagedOrDefective: "Si recibes un producto defectuoso, dañado o diferente al solicitado, contáctanos con tu número de pedido y fotografías o un vídeo que muestre el problema. Revisaremos tu caso y te indicaremos la solución correspondiente.",
};

export const MARKETS: Record<CountryCode, MarketConfig> = {
  CO: {
    countryCode: 'CO',
    countryName: 'Colombia',
    flag: '🇨🇴',
    currencyCode: 'COP',
    currencySymbol: '$',
    price: 189900,
    formattedPrice: '$189.900',
    compareAtPrice: 250000,
    formattedCompareAtPrice: '$250.000',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CO',
    plugType: 'US',
    plugName: 'Enchufe US (Tipo A/B)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  MX: {
    countryCode: 'MX',
    countryName: 'México',
    flag: '🇲🇽',
    currencyCode: 'MXN',
    currencySymbol: '$',
    price: 899,
    formattedPrice: '$899',
    compareAtPrice: 1199,
    formattedCompareAtPrice: '$1.199',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-MX',
    plugType: 'US',
    plugName: 'Enchufe US (Tipo A/B)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  PE: {
    countryCode: 'PE',
    countryName: 'Perú',
    flag: '🇵🇪',
    currencyCode: 'PEN',
    currencySymbol: 'S/',
    price: 239,
    formattedPrice: 'S/ 239',
    compareAtPrice: 319,
    formattedCompareAtPrice: 'S/ 319',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-PE',
    plugType: 'US',
    plugName: 'Enchufe US (Tipo A/B)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  CL: {
    countryCode: 'CL',
    countryName: 'Chile',
    flag: '🇨🇱',
    currencyCode: 'CLP',
    currencySymbol: '$',
    price: 54900,
    formattedPrice: '$54.900',
    compareAtPrice: 72900,
    formattedCompareAtPrice: '$72.900',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CL',
    plugType: 'EU',
    plugName: 'Enchufe EU (Tipo C)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  AR: {
    countryCode: 'AR',
    countryName: 'Argentina',
    flag: '🇦🇷',
    currencyCode: 'ARS',
    currencySymbol: '$',
    price: 134900,
    formattedPrice: '$134.900',
    compareAtPrice: 179900,
    formattedCompareAtPrice: '$179.900',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-AR',
    plugType: 'AU',
    plugName: 'Enchufe Tipo I',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  CR: {
    countryCode: 'CR',
    countryName: 'Costa Rica',
    flag: '🇨🇷',
    currencyCode: 'CRC',
    currencySymbol: '₡',
    price: 27900,
    formattedPrice: '₡27.900',
    compareAtPrice: 36900,
    formattedCompareAtPrice: '₡36.900',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CR',
    plugType: 'US',
    plugName: 'Enchufe US (Tipo A/B)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  ES: {
    countryCode: 'ES',
    countryName: 'España',
    flag: '🇪🇸',
    currencyCode: 'EUR',
    currencySymbol: '€',
    price: 49.90,
    formattedPrice: '49,90 €',
    compareAtPrice: 69.90,
    formattedCompareAtPrice: '69,90 €',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-ES',
    plugType: 'EU',
    plugName: 'Enchufe EU (Tipo C/F)',
    shippingPolicy: {
      ...defaultShippingPolicy,
      disclaimer: "Los plazos de entrega son estimados y pueden verse afectados por transportistas u otras circunstancias ajenas a nuestro control.",
    },
    returnsPolicy: {
      condition: "Las condiciones de desistimiento y devolución se gestionan de acuerdo con la legislación vigente de protección al consumidor en España y la Unión Europea.",
      instructions: "Si deseas gestionar una devolución, contáctanos antes de enviar cualquier paquete para orientarte sobre el procedimiento correspondiente.",
    },
    warrantyPolicy: {
      damagedOrDefective: "Si recibes un producto defectuoso, dañado o con falta de conformidad, contáctanos con tu número de pedido y fotos o vídeo del estado del artículo para evaluar la solución o sustitución conforme a la garantía legal aplicable.",
    },
  },
};

export const AVAILABLE_MARKETS: MarketConfig[] = [
  MARKETS.CO,
  MARKETS.MX,
  MARKETS.PE,
  MARKETS.CL,
  MARKETS.AR,
  MARKETS.CR,
  MARKETS.ES,
];
