import { CountryCode, MarketConfig } from '../types/market';

export const DEFAULT_COUNTRY_CODE: CountryCode = 'CO';

const defaultShippingPolicy = {
  processingTime: "Tiempo estimado de entrega informado por la logística: 15–20 días hábiles.",
  deliveryEstimate: "Recibirás tu número de guía para consultar el estado y rastrear tu pedido en línea hasta la entrega.",
  disclaimer: "Los tiempos de entrega son estimados y están sujetos a la operación del transporte terrestre nacional.",
};

const defaultReturnsPolicy = {
  condition: "Si deseas tramitar un cambio o devolución, contáctanos antes de enviar el producto para indicarte el procedimiento.",
  instructions: "Escríbenos directamente con tu número de pedido para recibir las instrucciones correspondientes.",
};

const defaultWarrantyPolicy = {
  damagedOrDefective: "Si recibes un producto defectuoso, dañado o diferente al solicitado, contáctanos con tu número de pedido y fotografías o un video que muestre el problema. Revisaremos tu caso y te indicaremos la solución correspondiente.",
};

export const MARKETS: Record<CountryCode, MarketConfig> = {
  CO: {
    countryCode: 'CO',
    countryName: 'Colombia',
    flag: '🇨🇴',
    currencyCode: 'COP',
    currencySymbol: '$',
    price: 199900,
    formattedPrice: '$199.900',
    compareAtPrice: 300000,
    formattedCompareAtPrice: '$300.000',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CO',
    plugType: 'US',
    plugName: 'Enchufe estándar de clavija plana (110 V)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  MX: {
    countryCode: 'CO',
    countryName: 'Colombia',
    flag: '🇨🇴',
    currencyCode: 'COP',
    currencySymbol: '$',
    price: 199900,
    formattedPrice: '$199.900',
    compareAtPrice: 300000,
    formattedCompareAtPrice: '$300.000',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CO',
    plugType: 'US',
    plugName: 'Enchufe estándar de clavija plana (110 V)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  PE: {
    countryCode: 'CO',
    countryName: 'Colombia',
    flag: '🇨🇴',
    currencyCode: 'COP',
    currencySymbol: '$',
    price: 199900,
    formattedPrice: '$199.900',
    compareAtPrice: 300000,
    formattedCompareAtPrice: '$300.000',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CO',
    plugType: 'US',
    plugName: 'Enchufe estándar de clavija plana (110 V)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  CL: {
    countryCode: 'CO',
    countryName: 'Colombia',
    flag: '🇨🇴',
    currencyCode: 'COP',
    currencySymbol: '$',
    price: 199900,
    formattedPrice: '$199.900',
    compareAtPrice: 300000,
    formattedCompareAtPrice: '$300.000',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CO',
    plugType: 'US',
    plugName: 'Enchufe estándar de clavija plana (110 V)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  AR: {
    countryCode: 'CO',
    countryName: 'Colombia',
    flag: '🇨🇴',
    currencyCode: 'COP',
    currencySymbol: '$',
    price: 199900,
    formattedPrice: '$199.900',
    compareAtPrice: 300000,
    formattedCompareAtPrice: '$300.000',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CO',
    plugType: 'US',
    plugName: 'Enchufe estándar de clavija plana (110 V)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  CR: {
    countryCode: 'CO',
    countryName: 'Colombia',
    flag: '🇨🇴',
    currencyCode: 'COP',
    currencySymbol: '$',
    price: 199900,
    formattedPrice: '$199.900',
    compareAtPrice: 300000,
    formattedCompareAtPrice: '$300.000',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CO',
    plugType: 'US',
    plugName: 'Enchufe estándar de clavija plana (110 V)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
  ES: {
    countryCode: 'CO',
    countryName: 'Colombia',
    flag: '🇨🇴',
    currencyCode: 'COP',
    currencySymbol: '$',
    price: 199900,
    formattedPrice: '$199.900',
    compareAtPrice: 300000,
    formattedCompareAtPrice: '$300.000',
    shippingPrice: 0,
    shippingLabel: 'Envío GRATIS',
    locale: 'es-CO',
    plugType: 'US',
    plugName: 'Enchufe estándar de clavija plana (110 V)',
    shippingPolicy: defaultShippingPolicy,
    returnsPolicy: defaultReturnsPolicy,
    warrantyPolicy: defaultWarrantyPolicy,
  },
};

export const AVAILABLE_MARKETS: MarketConfig[] = [
  MARKETS.CO,
];
